# This is a basic workflow to help you get started with Actions

name: Test & Archive

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clean
        run: ./gradlew clean --refresh-dependencies --stacktrace

      - name: Assemble Artifacts
        run: ./gradlew --stacktrace assembleFips_offRelease   
        
      - name: Test Release
        run: ./gradlew --stacktrace testFips_offRelease

      - name: Generate JavaDocs
        run: ./gradlew dokkaJavadoc

      - name: Generate Sources
        run: ./gradlew sourcesJar
        
      - name: Archive Library Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: library-artifacts
          path: app/build/outputs/aar/

      - name: Archive Javadocs
        uses: actions/upload-artifact@v2
        with:
          name: javadocs
          path: javadocs/

      - name: Archive Sources
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: sources/

